### ISSUE TITLE
Adicionar .gitignore ao projeto

### ISSUE THREAD

**Issue by nic** [maikvinicius/event-manager#1]
Uma mesclagem de https://github.com/github/gitignore/blob/master/Node.gitignore com https://github.com/github/gitignore/blob/master/Global/macOS.gitignore deve ser suficiente.

**Comment by nic** [comment]
BTW: Isso deveria estar na raiz: https://github.com/maikvinicius/event-manager/blob/master/EventManager/.gitignore

**Comment by maikvinicius** [comment]
Vou adicionar e ajustar no próximo commit. Valeeu 😄
