### ISSUE TITLE
Colocar EventManager como raiz do projeto

### ISSUE THREAD

**Issue by nic** [maikvinicius/event-manager#2]
Isso deveria ser a raiz do projeto: https://github.com/maikvinicius/event-manager/tree/master/EventManager e não dentro de uma sub-pasta.

**Comment by maikvinicius** [comment]
Ajustado no último [commit](https://github.com/maikvinicius/event-manager/commit/c687115a30018fb26e785b3a93b20f25364ac90e), muito obrigado!!!! 😄 😄
